export const cryptobet = {
  bitcoin: {},
  ethereum: {},
  solana: {},
  cardano: {},
  aptos: {},
  dogecoin: {},
  xrp: {},
  binance: {},
  litecoin: {},
  monero: {},
  degen: {},
  sui: {},
  stacks: {},
}